<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\Pretendard-Regular.ttf" />
    <Resource Include="Assets\Fonts\Pretendard-Medium.ttf" />
    <Resource Include="Assets\Fonts\Pretendard-Bold.ttf" />
    <Resource Include="Assets\Images\img_ci_mark.png" />
  </ItemGroup>

</Project>
